### ISSUE TITLE
another script for the domain ... .to

### ISSUE THREAD

**Issue by aiamuzz** [looneytkp/popcorntime#1]
Hello,

Can you create another linux install script that will download and install popcorntime from this website ...

https://popcorn-time.to/linux64.html

thanks.

**Comment by looneytkp** [comment]
hi, sorry for the late feedback
i could write that for you, but the installation file on that website installs a very weird popcorntime for Linux. That was the first script i wrote and it was so bad...
i could still write it for you if you want to try it, should i ?
